name: PaperCardTip
version: '${project.version}'
main: cn.paper_card.paper_card_tip.PaperCardTip
api-version: '1.20'
folia-supported: true
author: Paper99
depend:
  - Database

commands:
  tip:
    permission: paper-card-tip.command

permissions:
  paper-card-tip.command:
    default: op
